### PR TITLE
Usgs/earthquake hazard tool#107

### PR DESCRIPTION
**Pull request by jdbrown-USGS**
Fixes usgs/earthquake-hazard-tool#107
- Directions for install on windows and OSX

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
- In README.md provide a link to an "Installation" page.
- On installation page, first step is prerequisites. Split this into a link for "Mac Prerequisites" and "Windows Prerequisites" and put these on their own pages.
  - These prerequisites involve the installation and configuration for things like node, postgresql, php, etc...
- Next on installation page continue to the common stuff for initializing the database, configuring the application and running grunt etc...
  - These steps should largely be the same between mac and windows so no need to separate, but hightlight things that may be different.

**Comment by jdbrown-USGS** [comment]
- README.md no links to  installation page which has general set up for both windows and mac. Specific instructions for windows and mac here there own pages.

**Comment by emartinez-usgs** [comment]
- Move "Prereq" stuff before the git clone command.
- Typo on windows prereq pate: "Open admin command promp and stop postgresSQL server..."
  - Should be: "Open admin command prompt and stop PostgreSQL server."
- Command to stop postgresql server is unclear, use a multi-line code block to clarify
  - Path to postgresql installation should be more like `C:\Program Files\PostgreSQL\9.2`
- Use consistent conventions for command line output (leading $ symbol or such)
- Move database installation out of dependencies section
- Note when creating the tablespace to use C:\...path_to_app\<data_dir>\<db_name> (or similar).
- Document how to deal with missing MSVCR110.dll
- Update "Run Pre-Install" section to match new prompts/answers.

**Comment by jdbrown-USGS** [comment]
- Moved Prereq stuff before git clone command
- Fixed typos, numbering, and spacing
- Usese a more consistent conventions
- Moved database installation out of dependencies section
- Added note for creating tablespace in windows
- Added info on what to do about missing dll file
- updated pre install instructions

**Comment by emartinez-usgs** [comment]
Going a different way.

**Pull request closed without merging**
