### PR TITLE
Nshm 63

### PR DESCRIPTION
**Pull request by jdbrown-USGS**
- Validates on change rather than blur (this fixes focusing issues when using blur). Checks for numbers from 1 to 5,000 anything else is invalid and will trigger a modal dialog box. That explains values that are valid and uses the TimeHorizonSliderView. The input box is given an error class that stays till the user inputs a valid value. The model is updated when a valid value is given.

### CODE REVIEW

**Comment by ehunter-usgs** [comment]
*js/TimeHorizonInputView./js*
 - Put error validation text into a <p> tag `div.innerHTML = 'Time Horizon value must be between 0 and 5,000.';`
 - Improve error validation text, tell the user what action to take. (i.e. click a button)
 - Do not use the TimeHorizonSliderView, error validation is not cleared correctly.

```
    _modal = ModalView(div, {
      title: 'Validation error',
      classes: ['modal-error'],
      buttons: [
        {
          callback: function () {
            _modal.hide();
          },
          text: 'Cancel'
        },
        {
          callback: function () {
            _this.model.set({'timeHorizon': 2475}, {'force': true});
          },
          text: '2% in 50 years'
        },
        {
          callback: function () {
            _this.model.set({'timeHorizon': 475}, {'force': true});
          },
          text: '10% in 50 years'
        }
      ]
    });
```
*example/TimeHorizonInputView.js*
 - add link back to the example page (see any other example page)

**Comment by jmfee-usgs** [comment]
Include the time horizon value in button text: `10% in 50 years (475 years)`

**Comment by emartinez-usgs** [comment]
@jmfee-usgs: Can you follow-up on your latest comments and potentially merge this PR?

**Comment by jdbrown-USGS** [comment]
Fixes #42

Included the time horizon value in button text and updated styles for buttons.

**Pull request merged**
